# Generated by Django 4.2.5 on 2024-07-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Address',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
